### ISSUE TITLE
Cannot even import coinbase

### ISSUE THREAD

**Issue by WACOMalt** [resy/coinbase_python3#3]
in python 3.4.2, when I use "import coinbase"

I get the following error:

`Traceback (most recent call last):`
`File "coinkiosk2.py", line 13, in <module>`
`import coinbase`
`File "C:\Python34\lib\site-packages\coinbase\__init__.py", line 8, in <module>`
`
`    from .CoinbaseOAuth import CoinbaseOAuth`
`  File "C:\Python34\lib\site-packages\coinbase\CoinbaseOAuth.py", line 10, in <m`
`odule>`
`    import requests`
`ImportError: No module named 'requests'`

**Comment by mcmontero** [comment]
Hi!  Thanks for contacting us.  If you execute this:

pip3 install requests

Or install the native Python requests package you should be fine.

Mike
