### ISSUE TITLE
Nothing is working for me.

### ISSUE THREAD

**Issue by Koncealed** [resy/coinbase_python3#4]
Hello, I just found this api, and am pretty confused. I followed the instructions, and put coinbase inside my site-packages, and nothing is working. Something as simple as this is not working either.

https://gist.github.com/anonymous/75b48032ea78d7c7520322b68ecc52d9 (The apis keys are in ,but just not here)
Errors: https://gist.github.com/anonymous/d7d39e678c29cdc46c34dbfa01ac771e

Hopefully you can help me out.

**Comment by jackjconner** [comment]
hi, I am also getting this error, have you figured out a fix to the issue?

**Comment by Koncealed** [comment]
@bigbabyjack, Honestly I just gave up on the project, and started a new one. If anything just use NodeJS
